alphagov/gds-tech-learning-pathway

career-path/junior.md
One of the competency files was renamed and I have updated the links to it in the junior.md file.
=> Fixing competency link

guides/datastores/elasticsearch.md
Some useful links are being shared on slack, and I wanted to capture
them somewhere before they disappear into the ether.
[Rendered version](https://github.com/alphagov/gds-tech-learning-pathway/blob/d77b673cca314c74ac4ba6ac8f1064bf48a03409/guides/datastores/elasticsearch.md)
=> Guide for elasticsearch

career-path/competencies/knowing-when-to-ask-for-help.md, career-path/junior.md, career-path/mid.md
first stab at this
also relates to #38
=> Knowing when to ask for help

career-path/competencies/sharing-knowledge-with-others.md
This is a first draft - what do people think? What do we want to say about this?
Update: [Second attempt here](https://github.com/alphagov/gds-tech-learning-pathway/blob/0d357337f6ee86873e996e21bd07f6f2f0b97e3c/career-path/competencies/sharing-knowledge-with-others.md)
=> Flesh out "sharing knowledge" competency

career-path/competencies/knowing-when-to-ask-for-help.md
Fixed some typo errors and added a suggestion.
=> Update to ask for help competency

career-path/competencies/owning-their-development-plan.md
Junior 20% time includes more than just working on a 20% project.
A 20% project is optional and does not necessarily have to benefit GDS, but should have some specific learning outcomes that will help them improve their skills.
=> Update to owning development plan competency

.circleci/config.yml, README.md, career-path/competencies/using-appropriate-testing-to-ensure-software-quality.md, resources/languages/puppet.md, resources/systems/networking.md
Fix some dead links and set up CircleCI (https://github.com/alphagov/gds-tech-learning-pathway/issues/31)
This uses https://github.com/dkhamsing/awesome_bot
=> Fix dead links

career-path/competencies/leading-on-stories.md, resources/user-story-template.md
To help understand whether a task is well defined, it might be a good idea to have a template of a well defined story. Although most teams have a template to fill in new stories they may not be publicly available.
=> Add user story template

inspiration-and-resources.md
This looks really interesting and might be worth emulating.
=> Add Patreon Engineering Levels to resources

resources/languages/javascript.md
Added some JavaScript language guidance.
=> Add JavaScript language information and learning materials

resources/languages/css.md
Fixing the rebase I tried to do on https://github.com/alphagov/gds-tech-learning-pathway/pull/67
=> Added CSS language information, getting started and learning resources

resources/security.mb
Addressing this issue - https://github.com/alphagov/gds-tech-learning-pathway/issues/14
=> Add content on security

resources/handling-incidents.md
Resolves https://github.com/alphagov/gds-tech-learning-pathway/issues/16
=> Add Etsy's guide for incident reviews

resources/languages/java.md
https://github.com/alphagov/gds-tech-learning-pathway/issues/5
=> Java guide (WIP)

career-path/competencies/designing-for-reliability.md, resources/systems/reliability-engineering.md
And add the google book to it. Resolves https://github.com/alphagov/gds-tech-learning-pathway/issues/15
=> Add resource list for reliability engineering

Gemfile.lock, config/tech-docs.yml
Add search functionality as per version 1.5.0 of the `tech-docs-gem` (https://github.com/alphagov/tech-docs-gem/pull/28)
=> Enable search functionality

source/career-path/competencies/planning-and-estimating.html.md.erb
First draft of some words about estimating and planning competencies.
=> Add planning and estimating first draft

source/resources/code-reviews.html.md.erb
Add a code review doc with a brief explanation of what a code review is and why we do them.
Add some (hopefully!) useful tips for reviewing code and having code reviewed and links that I found useful in writing this.
=> Add code reviews doc

source/resources/version-control.html.md.erb
Add links to guides/tutorials on how to perform some of the noted git tasks
and workflows.
=> Add links to version control resource

config/tech-docs.yml
Address this issue: https://github.com/alphagov/gds-tech-learning-pathway/issues/115
=> Add contribution banner

source/career-path/leading-and-communicating/leading-on-stories.html.md
I've reviewed this document and it still looks good. I've added line breaks in to make the bullet points show up, rather than getting a block of text with em dashes in it.
=> Improves readability

source/career-path/working-practices/building-software-as-a-team.html.md, source/career-path/working-practices/knowing-when-to-ask-for-help.html.md
For "building software as a team" I've lifted expectations for mid-level/senior from the GDS job
descriptions.
For "knowing when to ask for help" I've added a suggestion from @katstevens that seniors should lead by example.
=> Review pages

source/career-path/working-practices/owning-your-development-plan.html.md
I've taken out another 'etc' and expanded it. I've also added a hyperlink where there was just a link in parantheses.
=> Reviews and tweaks 'Owning your development plan'

source/career-path/leading-and-communicating/pair-programming.html.md
- Fixed a spelling error
- Expanded out 'etc' in line with the GOV.UK style guide
=> Fixes spelling error and expands etc

source/career-path/leading-and-communicating/leading-on-stories.html.md, source/career-path/leading-and-communicating/pair-programming.html.md, source/career-path/leading-and-communicating/sharing-knowledge-with-others.html.md, source/career-path/technical-skills/designing-for-reliability.html.md, source/career-path/technical-skills/using-appropriate-testing-to-ensure-software-quality.html.md, source/career-path/technical-skills/version-control.html.md, source/career-path/working-practices/building-software-as-a-team.html.md, source/career-path/working-practices/knowing-when-to-ask-for-help.html.md, source/career-path/working-practices/owning-your-development-plan.html.md, source/career-path/working-practices/planning-and-estimating.html.md
I've read through these in the last week and found them all useful.
Please see the commits for more details.
=> Review career path docs

resources/other/handling-incidents.html.md
need to flesh out the psychological/analytical factors
=> Add some narrative about handling incidents
